[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.139.5"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.139.5"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.139.5"
